# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/Dancing_Cells',
                'doc_host': 'https://dorshmil.github.io',
                'git_url': 'https://github.com/dorshmil/Dancing_Cells',
                'lib_path': 'Dancing_Cells'},
  'syms': {'Dancing_Cells.core': {'Dancing_Cells.core.foo': ('core.html#foo', 'Dancing_Cells/core.py')}}}
